version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker run --rm --privileged multiarch/qemu-user-static:register
            docker build -t robertbeal/nfc-do .

workflows:
  version: 2
  commit:
    jobs:
      - build
